theme = "solarized_dark"

# [editor]
# gutters = [ "diagnostics" ] No way to toggle line-numbers at runtime so leave them on

[keys.normal]
C-j = ["move_line_down", "move_line_down"]
C-k = ["move_line_up", "move_line_up"]
